# Generated by Django 3.2.3 on 2021-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=10)),
                ('birth_date', models.CharField(max_length=12)),
                ('adhaar_number', models.CharField(max_length=12)),
                ('permission', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('address_1', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
