# Generated by Django 3.2.3 on 2021-06-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_info',
            fields=[
                ('health_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('blood_grp', models.CharField(max_length=10)),
                ('emergency_num', models.CharField(max_length=10)),
                ('medication', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='phone_number',
            fields=[
                ('phone_number_id', models.CharField(default='PN0001', max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('file_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=10)),
                ('symptoms', models.CharField(max_length=10)),
                ('diagnosis', models.CharField(max_length=10)),
                ('prescribed_medicine', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=10)),
                ('created_date', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
