# Generated by Django 3.2.3 on 2021-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_health_info_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adhaar_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='permission',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
