# Generated by Django 3.2.3 on 2021-06-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210608_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('health_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('blood_grp', models.CharField(max_length=10)),
                ('emergency_num', models.CharField(max_length=10)),
                ('medication', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_number_id', models.CharField(default='PN0001', max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='health_info',
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='diagnosis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='notes',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='prescribed_medicine',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='symptoms',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='file',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
