# Generated by Django 3.2.3 on 2021-06-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_allergiestable_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patient_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='paramedics',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
        migrations.AlterField(
            model_name='verifiedby',
            name='doctor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
