# Generated by Django 3.2.3 on 2021-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
